title: Valerie Teo  
#logo: 
#description: text below image
show_downloads: true
theme: jekyll-theme-minial
#https://pages.github.com/themes/

### Education 
Hello

### Work Experience
Hello
-1
-2
-3

### Projects
Hello
